### ISSUE TITLE
Sheet and Workbook Level Modules

### ISSUE THREAD

**Issue by imranosoft** [DanwareCreations/VbaModuleManager#1]
Hi,

Thanks for such a great tool. It really has the benefits mentioned in the repository. However I felt that this will not be entertaining for code behind worksheets/Thisworkbook i.e Events Modules. 

Best Regards
Imran Bhatti

**Comment by Rabadash8820** [comment]
@imranBh Glad it's helping you!

If you're saying that the VBA code in your sheets/workbook is not being imported/exported, then you are correct; the Module Manager explicitly ignores those types of modules. I did this because the recommended way to "install" the Module Manager is by importing it into a workbook and then adding calls to it in the workbook module. If Module Manager "managed" that code, then it would essentially break its own integration!

The recommended workaround is to move code out of your sheet/workbook modules and into their own standalone modules. This is good for a number of reasons, like giving you a chance to organize large subroutines/functions into their own modules for more navigable code, and reducing complexity in the sheet/workbook modules until they are just entrypoints into other, higher-level VBA code. Those entrypoints won't be imported/exported by Module Manager, but they will still be saved in your workbook. It's a bummer that this prevents _versioning_ of sheet/workbook module code, I admit, but in my experience, those event handlers don't change very often anyway, as long as all they do is call other high-level code.

**Comment by Rabadash8820** [comment]
@imranBh Since it's been a while, I'm going to close this Issue. We can re-open it if you have any other related questions/concerns.
